general:
  collectTelemetryData: false
  verbose: true
steps:
  gctsDeploy:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'WRGCST21_0'
    repository: 'dreamer-nv-wrgcts21_0'
  gctsExecuteABAPUnitTests:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'WRGCST21_0'
    repository: 'dreamer-nv-wrgcts21_0'
  gctsRollback:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'WRGCST21_0'
    repository: 'dreamer-nv-wrgcts21_0' 
  abapEnvironmentRunATCCheck:
    abapCredentialsId: 'WRGCST21_0'
    host: 'gprd.sapds.ru:44300'
    atcConfig: 'atcconfig.yml'
    dockerPullImage: false
